# Generated by Django 4.0.3 on 2022-04-26 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choreographer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('song', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(blank=True)),
                ('choreographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.choreographer')),
                ('dance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dance')),
            ],
        ),
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('level', models.BigIntegerField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('dance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dance')),
            ],
        ),
    ]
