# Generated by Django 4.0.3 on 2022-05-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_choreographer_id_alter_dance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dance',
            name='spotify',
            field=models.URLField(blank=True),
        ),
    ]
