# Generated by Django 4.0.3 on 2022-05-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_dance_spotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dance',
            name='spotify',
            field=models.TextField(blank=True),
        ),
    ]
