# Generated by Django 4.0.3 on 2022-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_dance_spotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='dance',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dancer',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
