# Generated by Django 4.0.3 on 2022-05-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_dance_desc_dancer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.URLField(blank=True),
        ),
    ]
