# Generated by Django 4.0.3 on 2022-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_room_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
