# Generated by Django 4.0.3 on 2022-05-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='body',
            new_name='ballet',
        ),
    ]
