# Generated by Django 4.0.3 on 2022-04-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0007_alter_statusmessage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmessage',
            old_name='image_url',
            new_name='image',
        ),
    ]
