# Generated by Django 4.0.3 on 2022-04-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0008_rename_image_url_statusmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='mini_fb.profile'),
        ),
    ]
