# Generated by Django 4.0.3 on 2022-03-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_person_remove_quote_author_remove_quote_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.person'),
            preserve_default=False,
        ),
    ]
